services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: nestjs_comments_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nestjs_comments_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: nestjs_comments_db
      JWT_SECRET: yourStrongJwtSecretKey
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://postthread-backend.onrender.com
    restart: on-failure
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  db_data:
